// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: lighthouse.proto

package lighthouse

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LighthouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *LighthouseRequest) Reset() {
	*x = LighthouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lighthouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LighthouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LighthouseRequest) ProtoMessage() {}

func (x *LighthouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lighthouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LighthouseRequest.ProtoReflect.Descriptor instead.
func (*LighthouseRequest) Descriptor() ([]byte, []int) {
	return file_lighthouse_proto_rawDescGZIP(), []int{0}
}

func (x *LighthouseRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LighthouseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
}

func (x *LighthouseResult) Reset() {
	*x = LighthouseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lighthouse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LighthouseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LighthouseResult) ProtoMessage() {}

func (x *LighthouseResult) ProtoReflect() protoreflect.Message {
	mi := &file_lighthouse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LighthouseResult.ProtoReflect.Descriptor instead.
func (*LighthouseResult) Descriptor() ([]byte, []int) {
	return file_lighthouse_proto_rawDescGZIP(), []int{1}
}

func (x *LighthouseResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

var File_lighthouse_proto protoreflect.FileDescriptor

var file_lighthouse_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x11, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x10, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64,
	0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75,
	0x74, 0x32, 0x59, 0x0a, 0x11, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x1d, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x75,
	0x2d, 0x69, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x75, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lighthouse_proto_rawDescOnce sync.Once
	file_lighthouse_proto_rawDescData = file_lighthouse_proto_rawDesc
)

func file_lighthouse_proto_rawDescGZIP() []byte {
	file_lighthouse_proto_rawDescOnce.Do(func() {
		file_lighthouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_lighthouse_proto_rawDescData)
	})
	return file_lighthouse_proto_rawDescData
}

var file_lighthouse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lighthouse_proto_goTypes = []interface{}{
	(*LighthouseRequest)(nil), // 0: lighthouse.LighthouseRequest
	(*LighthouseResult)(nil),  // 1: lighthouse.LighthouseResult
}
var file_lighthouse_proto_depIdxs = []int32{
	0, // 0: lighthouse.LighthouseService.Run:input_type -> lighthouse.LighthouseRequest
	1, // 1: lighthouse.LighthouseService.Run:output_type -> lighthouse.LighthouseResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lighthouse_proto_init() }
func file_lighthouse_proto_init() {
	if File_lighthouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lighthouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LighthouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lighthouse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LighthouseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lighthouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lighthouse_proto_goTypes,
		DependencyIndexes: file_lighthouse_proto_depIdxs,
		MessageInfos:      file_lighthouse_proto_msgTypes,
	}.Build()
	File_lighthouse_proto = out.File
	file_lighthouse_proto_rawDesc = nil
	file_lighthouse_proto_goTypes = nil
	file_lighthouse_proto_depIdxs = nil
}
